stages:
  load_data:
    cmd: python pipelines/src/load_data.py ${data.filepath} ${data.processed}
    deps:
    - pipelines/src/load_data.py
    params:
    - data.filepath
    - data.processed
    outs:
    - ${data.processed}

  preprocess:
    cmd: python pipelines/src/preprocess_v2.py data/processed/train_test_data.csv data/processed/X_test.pt
     data/processed/X_train.pt data/processed/y_test.pt data/processed/y_train.pt
    deps:
    - data/processed/train_test_data.csv
    - pipelines/src/preprocess_v2.py
    params:
    - data.processed
    outs:
    - data/processed/X_test.pt
    - data/processed/X_train.pt
    - data/processed/y_test.pt
    - data/processed/y_train.pt

  train_model_linear:
    cmd: python pipelines/src/train_v2.py data/processed/X_train.pt data/processed/y_train.pt linear_cnn
    deps:
      - pipelines/src/train_v2.py
      - data/processed/X_train.pt
      - data/processed/y_train.pt
    params:
      - models.linear_cnn
    outs:
      - data/models/linear_cnn_model.pth

  train_model_convolutional:
    cmd: python pipelines/src/train_v2.py data/processed/X_train.pt data/processed/y_train.pt convolutional_cnn
    deps:
      - pipelines/src/train_v2.py
      - data/processed/X_train.pt
      - data/processed/y_train.pt
    params:
      - models.convolutional_cnn
    outs:
      - data/models/convolutional_cnn_model.pth

  evaluate_model_linear:
    cmd: python pipelines/src/evaluate_v2.py data/processed/X_test.pt data/processed/y_test.pt data/models/linear_cnn_model.pth
    deps:
      - data/processed/X_test.pt  
      - data/processed/y_test.pt
      - data/models/linear_cnn_model.pth
    params:
      - evaluation.batch_size  

  evaluate_model_convolutional:
    cmd: python pipelines/src/evaluate_v2.py data/processed/X_test.pt data/processed/y_test.pt data/models/convolutional_cnn_model.pth
    deps:
      - data/processed/X_test.pt  
      - data/processed/y_test.pt
      - data/models/convolutional_cnn_model.pth
    params:
      - evaluation.batch_size  
