stages:
  load_data:
    cmd: python3 pipelines/src/load_data.py data/raw/flare_data2_df.csv data/processed/train_test_data.csv
    deps:
    - data/raw/flare_data2_df.csv
    - pipelines/src/load_data.py
    params:
    - data.filepath
    - data.processed
    outs:
    - data/processed/train_test_data.csv

  preprocess:
    cmd: PYTHONPATH=. python3 pipelines/src/preprocess_v2.py data/processed/train_test_data.csv
      data/processed/X_train.pt data/processed/X_test.pt data/processed/y_train.pt
      data/processed/y_test.pt
    deps:
    - data/processed/train_test_data.csv
    - pipelines/src/preprocess_v2.py
    params:
    - data.processed
    outs:
    - data/processed/X_test.pt
    - data/processed/X_train.pt
    - data/processed/y_test.pt
    - data/processed/y_train.pt
